INSERT INTO TBL_PROMOCAO ( DESCRICAO, IS_ALL_INCLUSIVE, LOCAL, PRECO, QTD_DIAS)
VALUES ('Viagem de familia', false, 'Gramado', 1234.99, 6 );
INSERT INTO TBL_PROMOCAO ( DESCRICAO, IS_ALL_INCLUSIVE, LOCAL, PRECO, QTD_DIAS)
VALUES ('Viagem de ferias', true, 'Cancun', 14234.99, 5 );
INSERT INTO TBL_PROMOCAO( DESCRICAO, IS_ALL_INCLUSIVE, LOCAL, PRECO, QTD_DIAS)
VALUES ('Viagem religiosa', false, 'Bali', 20534.99, 10 );
INSERT INTO TBL_PROMOCAO ( DESCRICAO, IS_ALL_INCLUSIVE, LOCAL, PRECO, QTD_DIAS)
VALUES ('Viagem radical', true, 'Amazônia', 12334.99, 15 );